# Generated by Django 2.2.3 on 2019-09-12 08:09

import bboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[bboard.models.validate_even], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='entry', to='bboard.Rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, unique_for_date='published', validators=[django.core.validators.RegexValidator(regex='^.{4,}$')], verbose_name='Товар'),
        ),
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together={('title', 'published'), ('title', 'price', 'rubric')},
        ),
    ]
