# Generated by Django 2.2 on 2019-10-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20190912_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to='rubric',
        ),
    ]
